# Site settings
title: Travel Blog
email: ddempsey@cabrini.edu
description: My simple travel blog.
baseurl: "/travel-blog"
twitter_username: rca503
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Don Dempsey" # Set default author name
      categories: "Places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
